app = "eivissa-operations-bot"
primary_region = "fra"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  RUN_SCHEDULER = "true"
  TIMEZONE = "Europe/Budapest"
  PORT = "8000"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"