"""Standardize booking status to uppercase

Revision ID: 3f7f2f1a7a1b
Revises: d8b7c1a5ad9c
Create Date: 2025-08-10 23:27:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7f2f1a7a1b'
down_revision = 'd8b7c1a5ad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE bookings SET status = 'ACTIVE' WHERE status = 'Active'")
    op.execute("UPDATE bookings SET status = 'DEPARTED' WHERE status = 'Departed'")
    op.execute("UPDATE bookings SET status = 'CANCELLED' WHERE status = 'Cancelled'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE bookings SET status = 'Active' WHERE status = 'ACTIVE'")
    op.execute("UPDATE bookings SET status = 'Departed' WHERE status = 'DEPARTED'")
    op.execute("UPDATE bookings SET status = 'Cancelled' WHERE status = 'CANCELLED'")
    # ### end Alembic commands ###