"""Add reminders_sent to bookings

Revision ID: d8b7c1a5ad9c
Revises: 
Create Date: 2025-08-10 23:12:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b7c1a5ad9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminders_sent', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminders_sent')
    # ### end Alembic commands ###